### ISSUE TITLE
Allow to define global scoupe env vars

### ISSUE THREAD

**Issue by danylkaaa** [kindritskyiMax/lets#18]
Sometimes I need to reuse env vars. Now I need to copy/paste envs from cmd to cmd. I want to be able to define env vars once and than access them in my commands

**Comment by kindritskyiMax** [comment]
You can use global `env`. Then in each command, you will be able to use that env vars

**Comment by danylkaaa** [comment]
@kindritskyiMax, use case: I need to use colors in my cmd output, so I want to define global vars like `GREEN`, `NC` and than use them like this: 
```bash
echo "${GREEN}hello world${NC}
```

No I need to define this color vars in each command

**Comment by danylkaaa** [comment]
Also it will be great if I be able to use global defined `eval_env`

**Comment by kindritskyiMax** [comment]
Yes, exactly, global `env` suite your needs https://github.com/kindritskyiMax/lets#global-env.

Also global `eval_env` is in plans to implement
